# Generated by Django 4.0.2 on 2022-03-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('subgroup_id', models.AutoField(db_column='Subgroup_ID', primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('amount', models.CharField(blank=True, db_column='Amount', max_length=30, null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('entry_name', models.TextField(blank=True, db_column='Entry_Name', null=True, unique=True)),
            ],
            options={
                'db_table': 'ACCOUNTING',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(db_column='Department_ID', primary_key=True, serialize=False)),
                ('department_name', models.TextField(db_column='Department_Name', unique=True)),
            ],
            options={
                'db_table': 'DEPARTMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(db_column='EmployeeID', max_length=10, unique=True)),
                ('fname', models.CharField(blank=True, db_column='FName', max_length=16, null=True)),
                ('minit', models.CharField(blank=True, db_column='MInit', max_length=1, null=True)),
                ('lname', models.CharField(blank=True, db_column='LName', max_length=30, null=True)),
                ('ssn', models.CharField(db_column='SSN', max_length=9, unique=True)),
                ('street', models.TextField(blank=True, db_column='Street', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('zip', models.CharField(blank=True, db_column='ZIP', max_length=9, null=True)),
                ('supervisor_id', models.CharField(blank=True, db_column='Supervisor_ID', max_length=10, null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=12, null=True)),
            ],
            options={
                'db_table': 'EMPLOYEE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(blank=True, db_column='Inventory_ID', max_length=15, null=True, unique=True)),
                ('brand', models.TextField(blank=True, db_column='Brand', null=True)),
                ('model', models.TextField(blank=True, db_column='Model', null=True)),
                ('category', models.TextField(blank=True, db_column='Category', null=True)),
                ('condition', models.TextField(blank=True, db_column='Condition', null=True)),
                ('repair_notes', models.TextField(blank=True, db_column='Repair_notes', null=True)),
                ('event_id', models.CharField(blank=True, db_column='Event_ID', max_length=15, null=True)),
                ('checked_out_by', models.CharField(blank=True, db_column='Checked_out_by', max_length=10, null=True)),
            ],
            options={
                'db_table': 'EQUIPMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_column='Event_ID', max_length=15, unique=True)),
                ('venue', models.TextField(blank=True, db_column='Venue', null=True)),
                ('event_name', models.CharField(blank=True, db_column='Event_Name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'EVENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, db_column='Event_ID', max_length=15, null=True)),
                ('start_date', models.DateField(blank=True, db_column='Start_Date', null=True)),
                ('end_date', models.DateField(blank=True, db_column='End_Date', null=True)),
            ],
            options={
                'db_table': 'EVENT_DATE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(db_column='EmployeeID', max_length=10, unique=True)),
                ('password', models.TextField(db_column='Password')),
            ],
            options={
                'db_table': 'LOGIN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='Role_ID', primary_key=True, serialize=False)),
                ('role_name', models.TextField(blank=True, db_column='Role_Name', null=True, unique=True)),
            ],
            options={
                'db_table': 'ROLE',
                'managed': False,
            },
        ),
    ]
